//supabase urls
const SUPBASE_URL = process.env.NEXT_PUBLIC_PROJECT_URL;
const SUPABASE_SECRETE = process.env.NEXT_PUBLIC_PROJECT_SECRET;
const SUPABASE_PUBLIC_URL = process.env.NEXT_PUBLIC_PROJECT_PUBLIC;

//authorization

export { SUPABASE_PUBLIC_URL, SUPABASE_SECRETE, SUPBASE_URL };
